# Generated by Django 6.1 on 2026-08-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputs', models.JSONField()),
                ('ouput', models.JSONField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
