# Generated by Django 6.1 on 2026-08-14 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xgb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictionlog',
            old_name='inputs',
            new_name='input_data',
        ),
        migrations.RenameField(
            model_name='predictionlog',
            old_name='ouput',
            new_name='output_model',
        ),
    ]
